// frontend/src/components/chart/BarChart.vue
<template>
    <div style="height: 100%">
        <canvas :id="chartId"></canvas>
    </div>
</template>

<script>
import { Chart, registerables } from "chart.js";

Chart.register(...registerables);

export default {
    props: {
        chartId: {
            type: String,
            default: "bar-chart",
        },
        labels: {
            type: Array,
            required: true,
        },
        datasets: {
            type: Array,
            required: true,
        },
    },
    watch: {
        labels: "updateChart",
        datasets: "updateChart",
    },
    mounted() {
        this.renderChart();
    },
    methods: {
        renderChart() {
            const ctx = document.getElementById(this.chartId).getContext("2d");

            new Chart(ctx, {
                type: "bar",
                data: {
                    labels: this.labels,
                    datasets: this.datasets,
                },
                options: {
                    maintainAspectRatio: false,
                    plugins: {
                        legend: {
                            display: true,
                        },
                        tooltip: {
                            callbacks: {
                                label: function (context) {
                                    // Get the value from the dataset
                                    const value = context.raw;
                                    // Format the value with the rupee symbol
                                    return `₹${value.toFixed(2)}`;
                                },
                            },
                        },
                    },
                    scales: {
                        x: {
                            tickLength: 0,
                            drawOnChartArea: false,
                            ticks: {
                                tickLength: 0,
                                font: {
                                    size: 14,
                                },
                                color: "rgba(0, 0, 0, 0.8)",
                            },
                            grid: {
                                display: false,
                            },
                        },
                        y: {
                            tickLength: 0,
                            ticks: {
                                display: true,
                                callback: function (value) {
                                    return "₹" + value;
                                },
                            },
                            drawOnChartArea: false,
                            grid: {
                                color: "rgba(0, 0, 0, 0.3)",
                            },
                            border: {
                                display: false,
                                dash: [3, 3],
                            },
                        },
                    },
                },
            });
        },
        updateChart() {
            if (this.chart) {
                this.chart.data.labels = this.labels;
                this.chart.data.datasets = this.datasets;
                this.chart.update(); // Update the chart with new data
            }
        },
    },
};
</script>

<style scoped></style>

// frontend-react/src/components/Molecules/charts/BarChart.tsx
import React, { useEffect, useRef } from 'react'
import { Chart, registerables } from "chart.js";

Chart.register(...registerables);

interface ChartProps {
    chartId: string;
    labels: string[];
    datasets: any;
}

const BarChart: React.FC<ChartProps> = ({ chartId, labels, datasets }) => {

    const chartRef = useRef<HTMLCanvasElement | null>(null);
    const chartInstance = useRef<Chart | null>(null);

    useEffect(() => {
        // Render the chart when the component mounts
        renderChart();

        // Cleanup chart instance when the component unmounts
        return () => {
            if (chartInstance.current) {
                chartInstance.current.destroy();
            }
        };
    }, []);

    useEffect(() => {
        // Update the chart when props (labels or datasets) change
        if (chartInstance.current) {
            chartInstance.current.data.labels = labels;
            chartInstance.current.data.datasets = datasets;
            chartInstance.current.update();
        }
    }, [labels, datasets]);

    const renderChart = () => {
        const ctx = chartRef.current?.getContext("2d");
        if (!ctx) return;

        chartInstance.current = new Chart(ctx, {
            type: "bar",
            data: {
                labels,
                datasets,
            },
            options: {
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        display: true,
                    },
                    tooltip: {
                        callbacks: {
                            label: (context) => {
                                const value = context.raw as number;
                                return `₹${value.toFixed(2)}`;
                            },
                        },
                    },
                },
                scales: {
                    x: {
                        ticks: {
                            font: {
                                size: 14,
                            },
                            color: "rgba(0, 0, 0, 0.8)",
                        },
                        grid: {
                            display: false,
                        },
                    },
                    y: {
                        ticks: {
                            callback: (value) => `₹${value}`,
                        },
                        grid: {
                            color: "rgba(0, 0, 0, 0.3)",
                        },
                        border: {
                            display: false,
                            dash: [3, 3],
                        },
                    },
                },
            },
        });
    };


    return (
        <div style={{ height: "100%" }}>
            <canvas id={chartId} ref={chartRef}></canvas>
        </div>
    );
}

export default BarChart
