// frontend-react/src/layouts/AdminLayout.tsx
import React from 'react';
import { Outlet } from 'react-router-dom';
import TopBar from '@/components/Atoms/UI/TopBar';
import NavBar from '@/components/Atoms/UI/NavBar';

const AdminLayout: React.FC = () => {
    return (
        <div>
            <div className="flex mt-[4.7rem] md:mt-0">
                <NavBar />
                <div className="content">
                    <TopBar />
                    <div className="pt-5">
                        <Outlet />
                    </div>
                </div>
            </div>
            <main>

            </main>
        </div>
    );
};

export default AdminLayout;

// frontend/src/components/layouts/AdminLayout.vue
<template>
    <main>
        <div class="flex mt-[4.7rem] md:mt-0">
            <NavBar />
            <!-- BEGIN: Content -->
            <div class="content">
                <TopBar />
                <div class="pt-5">
                    <RouterView />
                </div>
            </div>
            <!-- END: Content -->
        </div>
    </main>
</template>

<script>
import TopBar from "@/components/ui/TopBar.vue";
import NavBar from "@/components/ui/NavBar.vue";

export default {
    name: "AdminLayout",
    components: {
        TopBar,
        NavBar,
    },
    beforeMount() {
        document.body.classList.add("py-5");
    },
    beforeUnmount() {
        document.body.classList.remove("py-5");
    },
};
</script>
