// frontend/src/components/ui/PageTitle.vue
<template>
    <div class="intro-y flex flex-col sm:flex-row items-center justify-between">
        <h2 class="mr-5 truncate text-lg font-medium">
            {{ routeMetaTitle }}
        </h2>
        <button
            class="btn btn-primary shadow-md"
            v-if="isBackButtonAllow"
            @click="goBack"
        >
            <Undo2 />
        </button>
    </div>
</template>

<script>
import { Undo2 } from "lucide-vue-next";
export default {
    name: "PageTitle",
    components: {
        Undo2,
    },
    props: {
        isBackButtonAllow: {
            type: Boolean,
            default: false,
        },
    },
    computed: {
        routeMetaTitle() {
            return this.$route.meta.title;
        },
    },
    methods: {
        goBack() {
            this.$router.go(-1);
        },
    },
};
</script>

// frontend-react/src/components/Atoms/UI/PageTitle.tsx
import { Undo2 } from "lucide-react";
import { useNavigate } from "react-router-dom";

interface PageTitleProps {
    className?: string;
    title?: string;
    isBackButtonAllow?: boolean;
}

const PageTitle: React.FC<PageTitleProps> = ({ className, isBackButtonAllow = false, title = document.title }) => {
    const navigate = useNavigate();
    const routeMetaTitle = title;

    const goBack = () => {
        navigate(-1);
    };

    return (
        <div className={`intro-y flex flex-col sm:flex-row items-center justify-between ${className}`}>
            <h2 className="mr-5 truncate text-lg font-medium">{routeMetaTitle}</h2>
            {
                isBackButtonAllow && (
                    <button className="btn btn-sm btn-primary shadow-md" onClick={goBack}>
                        <Undo2 />
                    </button>
                )
            }
        </div >
    );
};

export default PageTitle;
