// frontend-react/src/components/Molecules/charts/PieChart.tsx
import React, { useEffect, useRef } from 'react';
import { Chart, PieController, ArcElement, Tooltip, Legend } from 'chart.js';

Chart.register(PieController, ArcElement, Tooltip, Legend);

interface PieChartDataset {
    data: number[];
    backgroundColor: string[];
}

interface ChartProps {
    chartId: string;
    labels?: string[];
    datasets?: PieChartDataset[];
}

const PieChart: React.FC<ChartProps> = ({
    chartId,
    labels = ['Rent', 'Utilities', 'Groceries'],
    datasets = [{
        data: [5000, 2000, 3000],
        backgroundColor: ["#508D4E", "#059BFF", "#FF4069"]
    }]
}) => {
    const chartRef = useRef<HTMLCanvasElement | null>(null);
    const chartInstance = useRef<Chart<'pie'> | null>(null);

    useEffect(() => {
        // Render the chart when the component mounts
        renderChart();

        // Cleanup chart instance when the component unmounts
        return () => {
            if (chartInstance.current) {
                chartInstance.current.destroy();
            }
        };
    }, []);

    useEffect(() => {
        // Update the chart when labels or datasets change
        if (chartInstance.current) {
            chartInstance.current.data.labels = labels;
            chartInstance.current.data.datasets = datasets;
            chartInstance.current.update();
        }
    }, [labels, datasets]);

    const renderChart = () => {
        const ctx = chartRef.current?.getContext('2d');
        if (!ctx) return;

        chartInstance.current = new Chart<'pie'>(ctx, {
            type: 'pie',
            data: {
                labels: labels,
                datasets: datasets.map(dataset => ({
                    ...dataset,
                    data: dataset.data,
                })),
            },
            options: {
                responsive: true,
                maintainAspectRatio: true,
                plugins: {
                    legend: {
                        display: true,
                    },
                    tooltip: {
                        callbacks: {
                            label: function (context) {
                                const value = context.raw as number;
                                return `₹${value.toFixed(2)}`;
                            },
                        },
                    },
                },
            },
        });
    };

    return (
        <div style={{ width: '190px', height: '190px' }}>
            <canvas id={chartId} ref={chartRef}></canvas>
        </div>
    );
};

export default PieChart;

// frontend/src/components/chart/PieChart.vue
<template>
    <div style="width: 100%">
        <canvas :id="chartId" style="height: auto"></canvas>
    </div>
</template>

<script>
import { Chart, registerables } from "chart.js";

Chart.register(...registerables);

export default {
    props: {
        chartId: {
            type: String,
            default: "pie-chart",
        },
        labels: {
            type: Array,
            required: true,
        },
        datasets: {
            type: Array,
            required: true,
        },
    },
    data() {
        return {
            chart: null, // Store the Chart instance
        };
    },
    watch: {
        labels: "updateChart",
        datasets: "updateChart",
    },
    mounted() {
        this.renderChart();
    },
    methods: {
        renderChart() {
            const ctx = document.getElementById(this.chartId)?.getContext("2d");

            if (ctx) {
                this.chart = new Chart(ctx, {
                    type: "pie",
                    data: {
                        labels: this.labels,
                        datasets: this.datasets,
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: true,
                        plugins: {
                            legend: {
                                display: false,
                            },
                            tooltip: {
                                callbacks: {
                                    label: function (context) {
                                        const value = context.raw;
                                        return `₹${value.toFixed(2)}`;
                                    },
                                },
                            },
                        },
                    },
                });
            } else {
                console.error(
                    `Canvas element with id '${this.chartId}' not found.`
                );
            }
        },
        updateChart() {
            if (this.chart) {
                this.chart.data.labels = this.labels;
                this.chart.data.datasets = this.datasets;

                // Ensure the chart is updated correctly
                this.chart.update();
            }
        },
    },
};
</script>

<style scoped></style>
